version: '2'

services:
  webserver:
    container_name: webserver
    image: 'apache:v1'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/lib/docker/volumes/apacheapp:/apacheapp
